account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    #path('', views.test_login, name='test_login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views as test_views
from blog_app import views as blog_views

urlpatterns = [
    path('', blog_views.post_list, name='index'),
    path('blog/', include('blog_app.urls',)),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
]

blog_app/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail,name='post_detail'),
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('create', views.create_post, name='create_blog')
]

blog_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now())
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager()
    
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,self.publish.month, self.publish.day, self.slug])
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80) 
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True) # 关闭不当评论

    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return '{}：{}'.format(self.name, self.post)

account/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class userRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='密码', widget=forms.PasswordInput)
    password_repeat = forms.CharField(label='再次输入', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
    
    def clean_password_repeat(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password_repeat']:
            raise forms.ValidationError(r"Password don't match.")
        return cd['password_repeat']

blog_app/forms.py
from django import forms
from .models import Comment, Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','body')

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','slug',
        'body','tags')

account/views.py
from django.shortcuts import render, HttpResponse
#from django.contrib.auth import authenticate, login
#from .forms import LoginForm
from django.contrib.auth.decorators import login_required
from .forms import LoginForm, userRegistrationForm
# Create your views here.

@login_required
def test_login(request):
    return render(request, 'account/test_login.html', {'section':'test_login'})

def register(request):
    if request.method == 'POST':
        user_form =  userRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'account/register_done.html', {'new_user':new_user})
    else:
        user_form = userRegistrationForm()

    return render(request, 'account/register.html',{'user_form':user_form})

blog_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import CommentForm, PostForm
#from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.auth.decorators import login_required

# Create your views here.

def post_list(request, tag_slug=None):

    object_list = Post.objects.all()
    # 获取 Tag
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) #实例化Paginator显示3页
    page = request.GET.get('page') #当前页面

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)   #页数非整数返回第一页
    except EmptyPage:
        posts = paginator.page(paginator.num_pages) #超过总页数返回最后一页
    return render(request, 'blog/list.html',{'page':page,'posts':posts,'tag':tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
        publish__year=year,publish__month=month,publish__day=day)
    
    # 列出对应评论
    comments = post.comments.filter(active=True)

    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # 创建数据对象但不保存
            new_comment = comment_form.save(commit=False)
            new_comment.post = post #外键为当前文章
            new_comment.save()  # 评论写入
    else:
        comment_form = CommentForm()
    
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_tags = Post.objects.all().filter(tags__in=post_tags_ids).exclude(id=post.id) #除去本文
    similar_post = similar_tags.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

    return render(request, 'blog/detail.html', 
        {'post':post, 'comments':comments,'new_comment':new_comment,
        'comment_form':comment_form, 'similar_posts':similar_post,
        'url_post':'/{}/{}/{}/{}/{}'.format('blog',year,month,day,post.slug)})
    '''
    return render(request, 'blog/detail.html', 
        {'post':post, 'comments':comments,'new_comment':new_comment,
        'comment_form':comment_form,
        'url_post':'/{}/{}/{}/{}/{}'.format('blog',year,month,day,post.slug)})
    '''

@login_required
def create_post(request):
    new_post = None

    if request.method == 'POST':
        post_form = PostForm(data=request.POST)
        if post_form.is_valid():
            new_post = post_form.save(commit=False)
            new_post.author = request.user
            
            new_post.save()
            for i in post_form.cleaned_data['tags']:
                new_post.tags.add(i)
    else:
        post_form = PostForm()
    
    return render(request, 'blog/create_post.html', {'post_form':post_form, 
      'new_post':new_post,})
    

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
    <head>
        <meta charset="utf-8">
        <link href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
        <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <div id="header">
            <span><a href="{% url 'index' %}">首页</a></span>
        </div>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/blog/create_post.html
{% extends 'base.html' %}
{% block title %}新建文章{% endblock %}

{% block content %}
    {% if new_post %}
        <p>文章已添加 <a href="{{new_post.get_absolute_url}}">查看该文章</a> 或 <a href="{% url 'index' %}">返回</a></p>
    {% else %}
        <h2>新建文章</h2>
        <form action="{% url 'blog:create_blog' %}" method="POST">
            {{ post_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="提交"></p>
        </form>
    {% endif %}

{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}
{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h1>{{ post.title}}</h1>
    {% if user.is_authenticated %}
        <p><a href="{% url 'logout' %}">登出</a></p>
    {% else %}
        <p><a href="{%  url 'login' %}">登录</a></p>
    {% endif %}

    <p class="date">
        {{ post.author }} 发布于 {{ post.publish }}
    </p>
    {{ post.body|linebreaks}}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize}}
        </h2>
    {% endwith %}

    <h2>推荐阅读</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        暂无推荐阅读
    {% endfor %}

    {% if new_comment %}
        <h2>评论已添加</h2>
    {% else %}
        <h2>新增评论</h2>
        <form action="{{ url_post }}" method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="提交"></p>
        </form>
    {% endif %}
    
    <h2>历史评论</h2>
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                <br/>
                {{ comment.name }} 发布于 {{ forloop.counter }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>暂无评论</p>
    {% endfor %}

{% endblock %}

templates/blog/list.html
{% extends "base.html" %}
{% block title %}首页{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <p><a href="{% url 'logout' %}">登出</a></p>
        <p><a href="{% url 'blog:create_blog' %}">新建文章</a></p>
    {% else %}
        <p><a href="{%  url 'login' %}">登录</a></p>
    {% endif %}
    {% for post in posts %}
        <div class="crow">
        <div class="col-md-3" style="background-color: #c7c7d6;box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;">
            <h2>
                <a href="{{post.get_absolute_url}}">
                    {{post.title}}
                </a>
            </h2>
            <h4>
                <p class="tags">
                    标签:{{ post.tags.all|join:", " }}
                </p>
                <p class="date">
                        {{ post.author}} 发表于 {{ post.publish }}
                </p>
            </h4>
            {{ post.body|truncatewords:30|linebreaks}}
        </div>
        </div>
    {% endfor %}
    <div class="crow">
        <div class="col-md-3" style="background-color: #c7c7d6;box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;">
            {% include "blog/pagination.html" with page=posts %}
        </div>
    </div>
{% endblock %}

templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number }}">Previous</a>
        {% endif %}
    </span>
    <span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>